### PR TITLE
cleanup code

### PR DESCRIPTION
**Pull request by rasheedamir**
clean code

### CODE REVIEW

**Comment by stakater-user** [comment]
@rasheedamir Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/workshop-operator/commit/70b4922c19f2af866b2f97cbb11dc759d3b2b1d6/checks) has Failed!

**Comment by stakater-user** [comment]
@rasheedamir Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/workshop-operator/commit/235ed2647d42cea2edf1d2898135f38e21640b22/checks) has Failed!

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull stakater/workshop-operator:SNAPSHOT-PR-19-606ed31c`

**Review by MaazMS — COMMENTED** [review]
pls delete heml also https://github.com/stakater/workshop-operator/blob/main/helm

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull stakater/workshop-operator:SNAPSHOT-PR-19-1a0c6012`

**Review by MaazMS — APPROVED** [review]

**Pull request merged**
