### PR TITLE
Delete operation of workshop-operator

### PR DESCRIPTION
**Pull request by MaazMS**
work in progress of Delete operation of workshop-operator , please do not merge to main.

### CODE REVIEW

**Comment by stakater-user** [comment]
@MaazMS Image is available for testing. `docker pull stakater/workshop-operator:SNAPSHOT-PR-22-86783a76`

**Comment by stakater-user** [comment]
@MaazMS Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/workshop-operator/commit/a6af12b0e0ec8b3999ba775bc2b466785bf0fd10/checks) has Failed!

**Comment by stakater-user** [comment]
@MaazMS Image is available for testing. `docker pull stakater/workshop-operator:SNAPSHOT-PR-22-3f2b8bbf`

**Comment by stakater-user** [comment]
@MaazMS Image is available for testing. `docker pull stakater/workshop-operator:SNAPSHOT-PR-22-39b8081d`

**Comment by stakater-user** [comment]
@MaazMS Image is available for testing. `docker pull stakater/workshop-operator:SNAPSHOT-PR-22-137a6c14`

**Comment by rasheedamir** [comment]
LGTM

**Review by rasheedamir — APPROVED** [review]

**Pull request merged**
