### PR TITLE
[WIP]create and update workshop-operator

### PR DESCRIPTION
**Pull request by MaazMS**
add method for create  and update workshop-operator resources.

### CODE REVIEW

**Comment by stakater-user** [comment]
@MaazMS Image is available for testing. `docker pull stakater/workshop-operator:SNAPSHOT-PR-25-99d3de04`

**Comment by stakater-user** [comment]
@MaazMS Image is available for testing. `docker pull stakater/workshop-operator:SNAPSHOT-PR-25-f087d0e2`

**Comment by stakater-user** [comment]
@MaazMS Image is available for testing. `docker pull stakater/workshop-operator:SNAPSHOT-PR-25-ae372f06`

**Comment by stakater-user** [comment]
@MaazMS Image is available for testing. `docker pull stakater/workshop-operator:SNAPSHOT-PR-25-f5197888`

**Comment by stakater-user** [comment]
@MaazMS Image is available for testing. `docker pull stakater/workshop-operator:SNAPSHOT-PR-25-c262452b`

**Comment by stakater-user** [comment]
@MaazMS Image is available for testing. `docker pull stakater/workshop-operator:SNAPSHOT-PR-25-e39c3b70`

**Comment by stakater-user** [comment]
@MaazMS Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/workshop-operator/commit/0d45f59e214160f8e097ad31c14dc41ebedc96ce/checks) has Failed!

**Comment by stakater-user** [comment]
@MaazMS Image is available for testing. `docker pull stakater/workshop-operator:SNAPSHOT-PR-25-7a88856a`

**Review by rasheedamir — APPROVED** [review]

**Pull request merged**
