### PR TITLE
delete method of nexus

### PR DESCRIPTION
**Pull request by MaazMS**
created delete method of nexus

### CODE REVIEW

**Comment by stakater-user** [comment]
@MaazMS Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/workshop-operator/commit/67529b9fa405f7e68b5a088647f7ff1a837c2bff/checks) has Failed!

**Comment by stakater-user** [comment]
@MaazMS Image is available for testing. `docker pull stakater/workshop-operator:SNAPSHOT-PR-26-a092deff`

**Comment by stakater-user** [comment]
@MaazMS Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/workshop-operator/commit/fb2135ba4aaec99ab625b39d83c82a23c69ffac9/checks) has Failed!

**Comment by stakater-user** [comment]
@MaazMS Image is available for testing. `docker pull stakater/workshop-operator:SNAPSHOT-PR-26-5d85e01f`

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull stakater/workshop-operator:SNAPSHOT-PR-26-4cfb62fc`

**Comment by stakater-user** [comment]
@MaazMS Image is available for testing. `docker pull stakater/workshop-operator:SNAPSHOT-PR-26-279b611a`

**Review by rasheedamir — APPROVED** [review]

**Pull request merged**
