### PR TITLE
Delete operation of pipelines

### PR DESCRIPTION
**Pull request by MaazMS**

### CODE REVIEW

**Comment by stakater-user** [comment]
@MaazMS Image is available for testing. `docker pull stakater/workshop-operator:SNAPSHOT-PR-36-06989f9d`

**Comment by stakater-user** [comment]
@MaazMS Image is available for testing. `docker pull stakater/workshop-operator:SNAPSHOT-PR-36-14f14cea`

**Comment by stakater-user** [comment]
@MaazMS Image is available for testing. `docker pull stakater/workshop-operator:SNAPSHOT-PR-36-f0c8098b`

**Comment by stakater-user** [comment]
@MaazMS Image is available for testing. `docker pull stakater/workshop-operator:SNAPSHOT-PR-36-4ffedb1e`

**Review by rasheedamir — APPROVED** [review]

**Pull request merged**
